#Sets some gps default verbose
#
/stcf/generator fGParticleSource
#/control/verbose 2
#/run/verbose 1
#/tracking/verbose 2

#
/gps/source/clear
/gps/source/add 1

/gps/position 0 0 0 m
/gps/direction 0.4 0.4 1.3
#x,y range: 374mm-735mm
#z: 1300 mm
/gps/particle pi-
/gps/energy 1.8653 GeV

/run/beamOn 1
#/run/beamOn 10000

/gps/particle proton
/gps/energy 1.2709 GeV
#/run/beamOn 10000

/gps/particle kaon-
/gps/energy 1.5663 GeV
#/run/beamOn 10000
